---
- name: Setup apache and open firewall port
  hosts: web
  become: true
  tasks:
    - name: Install apache packages
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Ensure apache is running
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Allow port 80 through UFW
      ufw:
        rule: allow
        port: '80'
        proto: tcp

